"""init

Revision ID: 4053f31b35f9
Revises: 
Create Date: 2022-12-24 15:44:36.346834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4053f31b35f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('bookmarks_hash', sa.String(length=255), nullable=True),
    sa.Column('bookmarks_per_page', sa.Integer(), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
