"""change struct

Revision ID: 4fe2af9d81de
Revises: 87ff1a730586
Create Date: 2022-12-22 15:57:48.289446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fe2af9d81de'
down_revision = '87ff1a730586'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('bookmarks_hash', sa.BigInteger(), nullable=True))
    op.drop_index('id', table_name='users')
    op.create_unique_constraint(None, 'users', ['user_id'])
    op.drop_column('users', 'tg_id')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('users', sa.Column('tg_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('id', 'users', ['id'], unique=False)
    op.drop_column('users', 'bookmarks_hash')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
