"""init

Revision ID: 59013334ae7c
Revises: 
Create Date: 2022-12-23 15:13:38.088790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59013334ae7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
