"""default value for is_subscribed

Revision ID: b09e21fcdc8c
Revises: 75a4fddb6e4a
Create Date: 2022-12-23 11:20:04.292026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b09e21fcdc8c'
down_revision = '75a4fddb6e4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
