"""unique user_id

Revision ID: bb6e5be357e8
Revises: c5bd79fd4bbf
Create Date: 2023-05-17 10:38:11.429931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6e5be357e8'
down_revision = 'c5bd79fd4bbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'supports', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supports', type_='unique')
    # ### end Alembic commands ###
